# # We have 2 stage Test and Deploy
stages:
  # - test
  - deploy

# # Test job
# test:
#   # Docker image
#   image: node:14-alpine
#   # Attach Test job to Test stage
#   stage: test
#   # Config to use GitLab Shared Runner with Executor Docker
#   tags:
#     - docker
#   script:
#     - echo "MONGO_URI"=$MONGO_URI_TEST > .env.test
#     - echo "JWT_SECRET"=$JWT_SECRET >> .env.test
#     - echo "GOOGLE_CLIENT_ID"=$GOOGLE_CLIENT_ID >> .env.test
#     - echo "GOOGLE_CLIENT_SECRET"=$GOOGLE_CLIENT_SECRET >> .env.test
#     - echo "GOOGLE_CALLBACK_URL"=$GOOGLE_CALLBACK_URL >> .env.test
#     - echo "FACEBOOK_CLIENT_ID"=$FACEBOOK_CLIENT_ID >> .env.test
#     - echo "FACEBOOK_CLIENT_SECRET"=$FACEBOOK_CLIENT_SECRET >> .env.test
#     - echo "FACEBOOK_CALLBACK_URL"=$FACEBOOK_CALLBACK_URL >> .env.test
# - echo "S3_ACCESS_KEY"=$S3_ACCESS_KEY >> .env.test
# - echo "S3_BUCKET"=$S3_BUCKET >> .env.test
# - echo "S3_SECRET_KEY"=$S3_SECRET_KEY >> .env.test
# - echo "S3_URL"=$S3_URL >> .env.test

#     - npm i
#     - npm run test
#   # Defines the names of branches and tags the job runs for
#   only:
#     - production

# Deploy job
deploy:
  type: deploy
  # Attach Deploy job to Deploy stage
  stage: deploy
  # Config to use our Runner with Executor Shell
  tags:
    - musicon
  script:
    # Only copy changed files to project folder
    - cp -r -u * $PROJECT_DIR
    - cd $PROJECT_DIR
    - echo "MONGO_URI"=$MONGO_URI_PRODUCTION > .env.production
    - echo "JWT_SECRET"=$JWT_SECRET >> .env.production
    - echo "GOOGLE_CLIENT_ID"=$GOOGLE_CLIENT_ID >> .env.production
    - echo "GOOGLE_CLIENT_SECRET"=$GOOGLE_CLIENT_SECRET >> .env.production
    - echo "GOOGLE_CALLBACK_URL"=$GOOGLE_CALLBACK_URL >> .env.production
    - echo "FACEBOOK_CLIENT_ID"=$FACEBOOK_CLIENT_ID >> .env.production
    - echo "FACEBOOK_CLIENT_SECRET"=$FACEBOOK_CLIENT_SECRET >> .env.production
    - echo "FACEBOOK_CALLBACK_URL"=$FACEBOOK_CALLBACK_URL >> .env.production
    - echo "FACEBOOK_CALLBACK_URL"=$FACEBOOK_CALLBACK_URL >> .env.production
    - echo "S3_ACCESS_KEY"=$S3_ACCESS_KEY >> .env.production
    - echo "S3_BUCKET"=$S3_BUCKET >> .env.production
    - echo "S3_SECRET_KEY"=$S3_SECRET_KEY >> .env.production
    - echo "S3_URL"=$S3_URL >> .env.production
    - npm i --only=prod
    # Restart NodeJS service
    - npm run stop || true
    - npm run start
  only:
    - production
